### Send PUT request with json body
DELETE http://localhost:8080/developer/Mini
Content-Type: application/json

{
  "developerLevel": "SENIOR",
  "developerSkillTYpe": "FULL_STACK",
  "experienceYears": 5
}